### ISSUE TITLE
Ошибка Failed to download the analyzer: authenticationrequired

### ISSUE THREAD

**Issue by sergiomarotco** [POSIdev-community/AI.Plugin.VSCode#1]
После успешной установки запускается плагин:
![image](https://user-images.githubusercontent.com/29877074/194107577-7bfc85f0-d64b-4436-aaab-6aa51055b6aa.png)
Получаю ошибку:
![image](https://user-images.githubusercontent.com/29877074/194107649-25efebb4-920b-46e8-a6de-831a78ded0bf.png)
EPERM: operation not permitted, unlink 'C:\Users\username\AI.INFRASTRUCTURE.INSTALLATOR.1.1.0.8741.zip'
Как победить?

**Comment by sergiomarotco** [comment]
Непонятно зачем вообще сохранять файл в корневую папку пользователя...

**Comment by alyadusov** [comment]
Похоже у вас есть ограничения на права для работы с корневой папкой пользователя. Файл вначале загружается в неё, а потом разархивируется в `%LOCALAPPDATA%\Application Inspector Analyzer`.  homedir была и выбрана для загрузки файла так как по умолчанию там не нужны никакие особые права при работе под разными OS. (Похоже нам нужно улучшить логику по выбору папки для загрузки к примеру для Windows брать Temp)

Сейчас как решение проблемы вы можете попробовать убрать ограничения на работу с файлами в папке пользователя, либо разово запустить под администратором vscode, либо скачать и разархивировать анализатор вручную.
Сделать это можно по этой ссылке - [скачать анализатор](https://update.ptsecurity.com/api/v6/products/AI.INFRASTRUCTURE.INSTALLATOR.zip/1.1.0.8741/download/AI.INFRASTRUCTURE.INSTALLATOR.1.1.0.8741.zip). После загрузки содержимое архива нужно поместить в `%LOCALAPPDATA%\Application Inspector Analyzer` и сделать рестарт плагина. (команда PT Application Inspector - Restart)
