### ISSUE TITLE
remote ssh

### ISSUE THREAD

**Issue by danilvoe** [POSIdev-community/AI.Plugin.VSCode#3]
Версия: 1.76.1
Фиксация: 5e805b79fcb6ba4c2d23712967df89a089da575b
Дата: 2023-03-08T16:31:31.010Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.15.72-un-def-alt1
Изолированные: No

Для разработки используется удаленное поключение через ssh ( https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh )  установил плагин и application inspector.

![Screenshot_20230323_145759](https://user-images.githubusercontent.com/15100792/227196718-84cd6b34-939b-49a0-aa06-656046ae0c4d.png)

но в меню нет пунктов связанных с плагином.

![Screenshot_20230323_145903](https://user-images.githubusercontent.com/15100792/227197226-a88ffe7b-3cfc-4126-8f96-7020498466e2.png)

Удаленная разработка не поддерживается?

**Comment by alyadusov** [comment]
Прошу прощения за долгий ответ. К сожалению такой фичи у нас пока нет - анализатор и код с которым идёт работа должны находиться на одной машине так, чтобы можно было работать с локальными физическими путями.

**Comment by danilvoe** [comment]
> Прошу прощения за долгий ответ. К сожалению такой фичи у нас пока нет - анализатор и код с которым идёт работа должны находиться на одной машине так, чтобы можно было работать с локальными физическими путями.

анализатор ставится плагином на удаленный сервер, его просто не видит плагин. 
![Screenshot_20230406_160327](https://user-images.githubusercontent.com/15100792/230386957-df7579ef-a782-4472-a8f4-016cf07bd557.png)

Может как то можно анализатор заставить из командной строки работать ?

**Comment by alyadusov** [comment]
> анализатор ставится плагином на удаленный сервер, его просто не видит плагин.

Думал, что это ssh подключение работает проще. Судя по документации vscode наше расширение должно уметь так делать сразу - сегодня поэкспериментирую у себя локально. Подскажите, пожалуйста, а у вас расширение стоит только на удалённом сервере? (так как если и там и там, то возможно при нажатии "Start scan" идёт попытка запустить локальный скан, вместо удалённого)

> Может как то можно анализатор заставить из командной строки работать ?

В таком виде использование анализатора плагинов не предполагается. Однако, в нашем enteprise решение есть Cli клиент.

**Comment by danilvoe** [comment]
> Подскажите, пожалуйста, а у вас расширение стоит только на удалённом сервере? (так как если и там и там, то возможно при нажатии "Start scan" идёт попытка запустить локальный скан, вместо удалённого)

расширение стоит только на удаленном сервере. Расширение по сути вообще не прогружается в интерфейсе vscode и нет команд команды для сканирования. (см изначальный пост и второй скриншот)
перечень доступных команд, сейчас - 

![Screenshot_20230413_130413](https://user-images.githubusercontent.com/15100792/231727055-037db8c8-0331-4869-b639-6428527d0b6b.png)

не помню был ли до появления обновления на плагин пункт со скачиванием.

**Comment by alyadusov** [comment]
Поэкспериментировал с последней релизной версией 1.3 и не удалось воспроизвести проблему. Через remote-ssh расширение отработало корректно. 
![image](https://user-images.githubusercontent.com/29537025/233872020-a55a6ec1-0b40-4546-893c-49526a1579cb.png)

@danilvoe, если у вас остались логи работы расширения или есть возможность попробовать еще раз (особенно было бы здорово если выставить логи в настройках расширения в Trace предварительно)  - не могли бы вы ими поделиться, пожалуйста?
В первую очередь интересуют логи из папки ./.ai/Logs/Infrastructure

**Comment by danilvoe** [comment]
@alyadusov извиняюсь за задержку в ответе.
складывается ощущение, что плагин вообще не погружается толком в случае ssh. 
ОС на хосте(на котором установлен vscode) alt linux 10.1 K

![Screenshot_20230504_120040](https://user-images.githubusercontent.com/15100792/236182342-b6115b9f-c3f7-4a02-8d9e-85e20720eff5.png)
![Screenshot_20230504_120011](https://user-images.githubusercontent.com/15100792/236182347-d3596c02-7546-45c4-8e41-fc7e10dd46f5.png)

**Comment by danilvoe** [comment]
[VSCode.zip](https://github.com/POSIdev-community/AI.Plugin.VSCode/files/11396774/VSCode.zip)

**Comment by danilvoe** [comment]
попросил коллегу проверить на ОС Windows, плагин прогрузился без проблем. получается проблема была не только в плагине и ssh но и в поддержки ОС.

**Comment by zero5** [comment]
Похоже, есть нюансы какие-то, но на Alt мы не проверяем, потому его пока и нет в списке поддерживаемых ОС.

**Comment by danilvoe** [comment]
@alyadusov  есть подвижки в сторону alt linux ? очень хочется ваш плагин использовать в работе.

**Comment by alyadusov** [comment]
@danilvoe, поддержка alt linux и данная проблема включены в список задач будущего релиза 2.1.0 (по срокам точно не скажу, но в этом году)

**Comment by donebd** [comment]
@danilvoe Обратился к вам  в телегармм по данной проблеме, мой ник в тг: https://t.me/donebd

**Comment by alyadusov** [comment]
Закрываю как решенную проблему.

Для истории:
Ошибки были связаны с нехваткой нужных библиотек на хосте. В таких случаях для поиска проблемы полезно запускать вручную из консоли исполняемый файл анализатора (infr).
