### ISSUE TITLE
Critical Error CoreNotFound

### ISSUE THREAD

**Issue by Transmittance** [POSIdev-community/AI.Plugin.VSCode#4]
<img width="376" alt="image" src="https://github.com/POSIdev-community/AI.Plugin.VSCode/assets/59690098/5ef14d36-c1da-4a97-86e8-e28343a1a0ad">

This error occures every time I run [PT AI] Smart Scan. What do I do?

**Comment by Transmittance** [comment]
<img width="786" alt="image" src="https://github.com/POSIdev-community/AI.Plugin.VSCode/assets/59690098/5a4dcdd5-1d35-41d0-a6d5-4f66a72b8ec6">

**Comment by Transmittance** [comment]
<img width="1032" alt="image" src="https://github.com/POSIdev-community/AI.Plugin.VSCode/assets/59690098/6fe4f64c-7b99-487e-9884-b2e4ef27fd10">

**Comment by vldF** [comment]
Have you updated the analyzer? [Here is an instruction](https://github.com/POSIdev-community/AI.Plugin.VSCode?tab=readme-ov-file#installing-the-code-analyzer)

If you have installed it manually, try delete the analyzer directory (/Library/Application-Inspector-Analyzer/ in your case) before and try install it again

**Comment by vldF** [comment]
Currently .net scanning isn't supported on macOS. You can disable scanning of C# code in `aiproj.json` file. 

To create the file, use a command `PT Application Inspector: Create Project Settings File`. Just remove the language from `ProgrammingLanguages` field, so, the analyzer will not try to start this core

**Comment by Transmittance** [comment]
Thank you, that has fixed the problem. Now I am able to proceed with scanning.
