### ISSUE TITLE
Downloading the analyzer: 26.77 MB/2.02 GB  Spending too much time

### ISSUE THREAD

**Issue by Carnival-z** [POSIdev-community/AI.Plugin.VSCode#6]
I found download the analyzer was too slow。 
![image](https://github.com/user-attachments/assets/e8dd0dbb-28ab-4ad0-a9ce-7480045a910d)
and sometime it will be stop in 1G or 1.06 or something else.
I want know i download the analyzer[https://update.ptsecurity.com/api/v6/products/AI.INFRASTRUCTURE.INSTALLATOR.zip/2.2.1.35411/download/AI.INFRASTRUCTURE.INSTALLATOR.2.2.1.35411.zip]  in web. 
Which directory should I put it in or unzip it to 。Or there are some parameters that can be set for him.

**Comment by alyadusov** [comment]
Hello!
Thank you for the signal, there really is something wrong with the server where we store the analyzers. Work on this is underway.

> Which directory should I put it in or unzip it to

![image](https://github.com/user-attachments/assets/93e4f85e-5b46-43e8-9ecc-bcd2d78ba56c)

I see that you are downloading an archive for Windows. Following our instructions, you should unzip this analyzer into a directory.
%LOCALAPPDATA%\Application Inspector Analyzer

**Comment by Carnival-z** [comment]
ok!thanks
