### ISSUE TITLE
[PT AI] Scan progress: Scanning is stuck at 1%

### ISSUE THREAD

**Issue by xsafetech** [POSIdev-community/AI.Plugin.VSCode#7]
When performing Java code scans, it's common to see the scanning status get stuck at 1% or 94%, does this have a direct impact on the code scan results?
![Uploading qq@2x.png…]()

**Comment by vldF** [comment]
Thanks for the issue!

There are some issues with the scan progress indicator. As far as I can understand the situation, they have only a visual impact. Scan results should not be affected.

Let me show you how our progress indicator works. We start multiple scanning cores simultaneously. Also, we check a file as scanned only when all cores mark it as scanned. So, if multiple scanning cores are running and they scan files in different order, we are stuck with that problem.

**Comment by xsafetech** [comment]
I am truly grateful for your explanation. I will continue to use this outstanding work, anticipating to uncover more security problems present in the code.
